ckpt: best-contrastive-sum
resume_dir: null
datadir: /disks/data/DatiMaltese/

# run_dir: outputs/${hydra:runtime.choices.model}_${hydra:runtime.choices.data}_${hydra:runtime.choices.data/motion_loader}

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 32
  num_workers: 8

gradient_accumulation_steps: 1

hydra:
  run:
    dir: runs_single/${hydra.job.override_dirname}
  sweep:
    dir: runs
    subdir: "data=${hydra:runtime.choices.data}/\
            model=${hydra:runtime.choices.model}/\
            translator=${hydra:runtime.choices.model/translator}/\
            loss=${hydra:runtime.choices.model/loss}/\
            finetuning=${hydra:runtime.choices.finetuning}/\
            lr=${model.lr}"
  job:
    config:
      override_dirname:
        # item_sep: /
        exclude_keys:
          - common_space_dim
          - data_rep

run_dir: ${hydra:runtime.output_dir}

defaults:
  - finetuning: disabled
  - data: coco_faceswap
  - model: idclip
  - trainer
  - defaults
  - _self_
