ckpt: best-contrastive-sum
resume: False

# run_dir: outputs/${hydra:runtime.choices.model}_${hydra:runtime.choices.data}_${hydra:runtime.choices.data/motion_loader}

batch_size: 32
gradient_accumulation_steps: 1
base_dir: runs

hydra:
  run:
    dir: runs_single/${hydra.job.override_dirname}
  sweep:
    dir: ${base_dir}
    subdir: "data=${hydra:runtime.choices.data}/\
            model=${hydra:runtime.choices.model}/\
            translator=${hydra:runtime.choices.model/translator}/\
            loss=${hydra:runtime.choices.model/loss}/\
            tok_position=${hydra:runtime.choices.data/train}/\
            training-setup=${hydra:runtime.choices.training_setup}/\
            finetuning=${hydra:runtime.choices.finetuning}/\
            lr=${model.lr}"
  job:
    config:
      override_dirname:
        # item_sep: /
        exclude_keys:
          - common_space_dim
          - data_rep

run_dir: ${hydra:runtime.output_dir}

defaults:
  - finetuning: disabled
  - data: coco_faceswap_5_entities
  - training_setup: with_entities
  - model: idclip
  - trainer
  - defaults
  - _self_
