trainer:
  _target_: pytorch_lightning.Trainer

  max_epochs: 10
  log_every_n_steps: 50
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  val_check_interval: 0.1
  accelerator: gpu
  devices: 1
  accumulate_grad_batches: ${gradient_accumulation_steps}

  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: latest-{epoch}
      every_n_epochs: 1
      save_top_k: 1
      save_last: false
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: best-contrastive-sum-{epoch}
      monitor: val_contrastive_t2i_sum_epoch
      mode: max
      save_on_train_epoch_end: false  # save after each validation step
      save_top_k: 1
      save_last: false
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: best-entities-sum-{epoch}
      monitor: val_entities_kmin_sum_epoch
      mode: max
      save_on_train_epoch_end: false  # save after each validation step
      save_top_k: 1
      save_last: false

    - _target_: src.callback.progress.ProgressLogger
      precision: 3
    - _target_: src.callback.tqdmbar.TQDMProgressBar

  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: ${run_dir}
    version: ""
    name: logs